apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nodegonnagiveyouup
  janus-idp.io/tekton: nodegonnagiveyouup
  backstage.io/kubernetes-id: nodegonnagiveyouup
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodegonnagiveyouup
resources:
- deployment.yaml
- route.yaml
- service.yaml
